export const Icons = {

    BAD_PASSWORD: "/icons/dark/bad-password.png",
    COMPUTER_OFFLINE: "/icons/dark/computer-offline.png",
    COMPUTER_ONLINE: "/icons/dark/computer-online.png",
    COPY_SUCCESSFUL: "/icons/dark/copy-success.png",
    COPY: "/icons/dark/copy.png",
    DISABLED_COMPUTER: "/icons/dark/disabled-computer.png",
    EDIT: "/icons/dark/edit.png",
    EXPIRED_PASSWORD: "/icons/dark/expired-password.png",
    IDLE: "/icons/dark/idle.png",
    MENU: "/icons/dark/menu.png",
    PLUS: "/icons/dark/Plus.png",
    PRINTER_OFFLINE: "/icons/dark/printer-offline.png",
    PRINTER_ONLINE: "/icons/dark/printer-online.png",
    DISABLED_PROFILE: "/icons/dark/disabled-profile.png",
    PROFILE: "/icons/dark/profile.png",
    REFRESH: "/icons/dark/refresh.png",
    SIMPLE_COPY_SUCCESSFUL: "/icons/dark/simple-copy-success.png",
    SIMPLE_COPY: "/icons/dark/simple-copy.png",
    TRASH_CAN: "/icons/dark/trash.png",
    COMPUTER: "/icons/dark/computer.png",
    DISTABLEDGROUP: "/icons/dark/disabled-group.png",
    GROUP: "/icons/dark/group.png",
    ADMIN: "/icons/dark/admin.png",
    PRINTER: "/icons/dark/printer.png",
    DRIVE: "/icons/dark/drive.png",

} as const;